from fastapi.testclient import TestClient

from simple_proxy.main import app


OPENAI_RESPONSE_BODY = {
    "choices": [
        {
            "finish_reason": "stop",
            "index": 0,
            "message": {"content": "This is generated by AI", "role": "assistant"},
        }
    ],
    "created": 1683130927,
    "id": "cmpl-7C9Wxi9Du4j1lQjdjhxBlO22M61LD",
}

client = TestClient(app)

def test_index():
    response = client.get("/")
    assert response.status_code == 200

    json = response.json()
    assert json["status"] is True


def test_request(httpx, response):

    url = "https://openai.com"

    httpx.return_value = response(json=OPENAI_RESPONSE_BODY)
    
    res = client.post(
        "/request", json={"url": url, "body": "request body"}, headers={"customer-header": "CUSTOM_HEADER"}
    )

    assert res.status_code == 200
    json = res.json()

    assert json
    assert json["choices"]

    (req,), _ = httpx.call_args

    assert req.method == "POST"
    assert req.url == url
    assert req.headers["customer-header"] == "CUSTOM_HEADER"
    assert req.content == b'{"body": "request body"}'
